name: CI

on: push
jobs:
  crates:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v3
      - id: set-dirs
        run: echo "dir=$(ls -d */ | jq -R -s -c 'split("\n")[:-1] | map(. | .[:-1])')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs:
      - crates
    strategy:
      matrix:
        dir: ${{fromJson(needs.crates.outputs.dir)}}
    steps:
      - uses: actions/checkout@v3
      - name: Unlock input
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Cache Cargo crates.io index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry/index
          key: cargo-crates.io-index

      - name: Check
        run: cargo check -p ${{ matrix.dir }}

      - name: Test
        run: cargo test -p ${{ matrix.dir }}

      - name: Clippy
        run: cargo clippy -p ${{ matrix.dir }} -- -D warnings
